---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: guava
spec:
  encryptedData:
    token: AgAo06zq7NJMLGjWzlyJABBCK7ujSNdBWCNZcDSZAjj5w2sCkM1+J6mPcE/eqHTTOuYzQAwoKxLbM4mdeCZzOQ6fPJvnezNEM02whC7kFgfPyctpqH+0T5PoRPQI529ZvBzsXnU9fX+FcVy320ZvKuMdIFJr6hrtyfYxPJNCbbRt3cmNpqwp2N5GoDOBR3CiS86Cy9Qgs2a7cSlEpISWxWTkLS3e2VMLcyFdXnssBdanGLg6QQv/5J+caVA3lTK88CoLWbtQVByRaQytODG9kwcdINFwzatujRYXjcz9tOpdt7SBBnFjbN2iO4+Hm0vKFUON/UCcdnnLpXKmfaJESFm2rUlF6m4jca5J0czhoGKpFZlSXq145rLBNWDDkbsupYuAlqNvWIHYjYM1QtZ1oEDj8kAHNm8JiEK01Pln9bLEXLyFJAfAhq1RptBBrYnFlt5LOU14Am0c66SnFujORMNZaEarW1/7Wz3jmLOG/Du7E6leE20+3gDHV732ApwxjHckSglPI/3o25mWLOrm2GsNMS96zRC3ds06OqkBCxtT/ZDf+LT81KjQmB6sW6Dru0GDa5gWf6IUee4c4RgIN1aUkgzI9njM7FV1x0Pux/QuHocJ3PBLPAh0i+Ll9ndbxLKcFxDeQGfx/BY+1wysm1z52XLW4a+tySea55llgFhxj26AgktdSAMuEFh76GtPM0zLC0DzinwEgdzScGRaDJwm61bEOFQvAeZ5VcfC2MlR1Q9IM36snAtIHUrdJarp3XNIVF/p/4P981lrdBXIKnar8V2W99wYuU0/tSL3H05NPELXjKJ6uoD8WAWJwH44oNM79ZQkXTjq8NDd29LCZ3Zhk6L/uWMNk5k7cSYWlkCYvV3VyiG03cjTq7x8oN6AlhXkDttpu10TSIOBTIGY3D6H758Wd9T1Cc2wNNV+FMgHitmdwsyRBsZB
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: guava
