apiVersion: ENC[AES256_GCM,data:Tnw=,iv:1BZbbqKQYLbydM8sAvj8W6Lt4hZTR3323p+f933gAx8=,tag:Q8ukkEUiDt25J1kdepWs0g==,type:str]
data:
    credentials.json: ENC[AES256_GCM,data:VJq8v3nWNHBWJwhLTqe51mN7LSwHDDwPkKm3HyhA9BGkpFPiECd/cj8gFZHGwCNMJvEzQtF7ThUPGHBojSApmf+6J2nfBbnJb1Mcdq2+DxuS/Eh1wJWPW5fRNPwc+/9qSZSbySHlbdjzzG2bXbQG3/UuosFxB5BfFVfdKI4itAKv+Nv+kWNZmN2UE+fkwAE/602HxrCiJA2P7RN9/LH7gPOd3PJTmZxOC42zZQrFkXnFMEN3rZo9Iyd62LBXDEwYWkVQP5ax/AsY+PSYCV8eS5wDIp4tz1f+xS9mRzt0UJ0Nhx3lB1dfNJLxjyA=,iv:vX3t2X7/pq5jLm5hitFPlr1G5s0EeqLWUGf5UBCN0to=,tag:oPu7aqKytbVCbP4EYleKZQ==,type:str]
kind: ENC[AES256_GCM,data:0BmapvHq,iv:q116bPzsWaVnRp3wUC0B6B0wYvONfMwI6IryH8X5Jts=,tag:q5cOVOyb4mKK/u2yWtRr5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4gfNVhsmByJ1K9zZhxdHNoWsuPBhnmI=,iv:sruD8jEOrbcbO21g8pKiKAY401YPghGiNvb4GAuEuGE=,tag:45Q7z5os4a+RvAtz3hZmig==,type:str]
    namespace: ENC[AES256_GCM,data:lPBcRPE=,iv:35l7tZrVL3ZojjpiBMRjU4xInR0qUsoWP0jkIHWSQF4=,tag:qSmYMpu6PzbS3GOSMKRGFA==,type:str]
    ownerReferences:
        - apiVersion: ENC[AES256_GCM,data:CJG2oisnjvc731wdjFpt3mZ8UAU=,iv:Wmk235xwqugW06MEyBleqeTqm2WsU77XgR4jj9dcyyg=,tag:2Xfgexow+xbALDERYl/52g==,type:str]
          controller: ENC[AES256_GCM,data:F9Zixg==,iv:EhCKi4qdf3c2NiyyjznONzTyr9fM8TPK9cKMbTz2u30=,tag:DwCt4Lhtx/Xxjp2/QzIfFQ==,type:bool]
          kind: ENC[AES256_GCM,data:tpycuH78z0lg3Xvh,iv:6/B4D+sUsX3pTfEDMqifZWkzBtqM9qLAUVTTvgQmMvQ=,tag:FTU4BsGVVDjyBJ1GbLR5nA==,type:str]
          name: ENC[AES256_GCM,data:dirf0oMX0j/TweAYwtq2BZFIBpbyhbQ=,iv:pn39OhaVVT84N4clnmtz/rEOm2J4hXJCeAWwxa5E27I=,tag:JJISDyxIXhZfnmJKY/sWLw==,type:str]
          uid: ENC[AES256_GCM,data:8XzfjIF3+jy+TL/QW74BwmxzAcT4Hrjk/Elc2Hio5UatUfHu,iv:RNpf3Qm8NZMjk0CbG8beqSSFLQso76k8dxM35qF04mc=,tag:qXfxKqPX/SxIqJtOe/x5qA==,type:str]
type: ENC[AES256_GCM,data:fiLirkxy,iv:24xmJGH4t9OBKhQ2QsEhMG9APLkZt0HT9iEDWItVXaQ=,tag:OAGU150EwUydJA4qzJEhVw==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRjd1dUIyK1YrS05qbmFX
            ZVFiMXhHUXdnVkdFTW5aeVBqR0xtRXc1bGwwCnBFbWk2MmNxVVNIWVpVQ1YreVBm
            eEJtV2M0VXVuMmFLNHpERzhWbERvZHMKLS0tIGxZbERwaHhLREJKbTlUbktjSzZx
            dzYzaE9EemNkOFlsbXFxZ04zQkdlR0UKSZm/xbpDmmVlUJwFtXOm46ksaI0qiNz7
            o0WI/vSoKy7EB4GNejJbs8qkbeZdZhdZ3hvD8+HGmTiPxyGNn2YqiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T04:13:50Z"
    mac: ENC[AES256_GCM,data:DVN9U/NFh9fHiWfAP8RhQGwCLuUgF6/PCZWql5iGcJhgVnUSG601Tc0xisf0823q/Y18Ox0yLGw6rbxMRFgmwrPTCelbK1HpJ7oLqtVpZdYU262ReQoiGPuD1o7PXsOWXWXukZI+lLDSq3srs8aRKk60BZ07cUeQMb1iOSgfCiU=,iv:E5nAdK0KC4x00AJ/eOfpz/aIKD4cmNv7Be4ZQT5n9PM=,tag:wDqlOIDI2+J97yQSziHPAg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
