---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: guava
spec:
  encryptedData:
    credentials.json: AgAgk/g9aKm3UYmFNUyORzUVKZCJizxw6wrJZUeG6X3u5ST3Jlq3Koxz6BBMw6vxXtw2TLPbmi03x+Brl2nVZLM8kOUHgTlR1UNCfs+tRkhZjuESOizoU9Ks1DiqMOQ/TYmIBxmVXcqRWm3v5LBrZWokJnpGZ883oOgd+zQBomYbgNm4wYHX2tlUoHpKpCj+rfQHcJa0KKhobzYE73TEsZ3+C/sL0JtwUUZbhCFyl4y+9pDo7/eg3dSaCcY+iqJxfYLDJdfnBLE2Yi0YxDZop5auQdFDB7ml56gQ00usbGLxgx0DNXHfwGXxGAsLnu07WD60QYY2Y0dJab8BN/35D36kNTJfFAHKKY6aGshIxLpwHwsRNtThNUs7LGz1wQrs3EnTKBbKsiTwbJw+g23E6OSCRwBW/5Hltqgm+liUs6tCj1UEE5mbhvZo8c+jrxqWSL/tL0pFiVwYPG0hYlvE9ly2x8eJRsWPAXzY2QvZLCHohF7o2HMSCIbg6yuYfY8QoPU8D0bn3OLuvt/gQNVOaIdykAqwm2EU2/Xq2aCUv+DsKu54VOjew56pDPYTnJz6x4Z7bacGHXNBNTMZxwYzfIbwaVWNTaRcz7or97OzYi8Pa9w3hXD61Hj0WQAU5PwBPxMi1ducNZSWv+GjAnarP99GkQb4R0+KQqFGDxaUpJEaMmk/zi1gPOlX4J9GDGEq5kA+LcidAoRubFsrh6SszPK8Cznc6FxbyJmWo3SFCNEpC8Ia/T6VQ9WA0WjmJwRqx5ejpZIeep3OAJO88a+lAog3p8xDWC8iGxjJt3qK/zYj8emPMGFotAXLRiHYtmfl6u4o0jH57HlpJWgIcL6lB1ALb9UQo+S5qpYJGlmX0CbGufiQDLW68wm9t0QRF1nGdqrLM+HI8Fbvxe4lbhGSIesPAswi75AjnaxVd86ZHRBf
  template:
    metadata:
      name: cloudflared-credentials
      namespace: guava
