apiVersion: ENC[AES256_GCM,data:9xk=,iv:lQkKwgpDgfxKE8CwT+aLWv5Gh10r6ASNiXXN6AyR8bU=,tag:X+qUFpwrcOhzAPKFXlOpKw==,type:str]
data:
    credentials.json: ENC[AES256_GCM,data:fJq6tJHS7Shh2M4EcWN8n3ZJxHmQ6VY8embfxT2OcMMAryNj+ndsufK1fseJ5//RkjXpYmiLx2CwKnBUlP+N8HeWMHXQKXBSFfs7Qg4HzXCu0H1IEBGGp1Fho4kSJoWlV6bKD/umNTapAbqv4S9EVSGuXobELBphZ4XZAnIVH+FpvIfRfmoAIKtfDCHDRf09XL3vtAC1Azy3W4tTWLMcSHH/f9UWBvD8pwqb/iMp18jIv30q7M5XLIuH6+TSJ21PyjSR3MNvleuqOT5AsMxRkji0PbxJO8NFQDqkuh0fS4IqIXMEcuvHYVbxTuo=,iv:VXvfN/BP+v8628jWiMindz9vx9xDK4WHq4rlhNvTGPg=,tag:ZY4Bd//pdHHP4yG/RK7geg==,type:str]
kind: ENC[AES256_GCM,data:S5DnSWj+,iv:XR+hty8YwMNdh0wCCKIO4buJd0i8+io/gMC8YUppfsk=,tag:GebkSgBEx/YelouutxT6Mg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Yevsq0/+dqhJ9pHXvF/ZTLS38ynqPLY=,iv:0SD2si/k5ZOwP3irWr3Lc4WroHlyoo2JA5R0MTHHHKA=,tag:zB5uwpc8qZm5W290aIP44w==,type:str]
    namespace: ENC[AES256_GCM,data:i/kvek8=,iv:K3EEmnVNaFPVmWHhhi7wAUQdmfB6qoeVYe1gm1LuwfE=,tag:B5Jul/+AYdH3p66vWinAIQ==,type:str]
type: ENC[AES256_GCM,data:sPIehyqY,iv:o7z8RWrW98P/Q7U0Uc0y2YA2tACjMRgh51bF2RrhA2Q=,tag:+wiMfDjCRPG2bQ4OonsWPQ==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWXZoYk9uN292aWFReWs0
            bG9SNnlVMTN3YVk0UVlLWUdZNldsamJZQURrCkdXWlFXQjBmUmUydXdabXBaaDE3
            bW9hSEdkeGIya2x5S3FDMEhrY2J6QUEKLS0tIEdmb212V09wY2ZKNmIyNDZTaDBY
            SXovTGl3aWJMaFg2elhqQkp0OW9HSHMKIbjzEjMjDHuMDTtMJ8qKS2UO8M3b1Qyx
            pp3qfL/wbIyyzwqKPf7eGaV3tyBN4xsrELoaHsVoAFMjN4VVe5ggrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T06:21:40Z"
    mac: ENC[AES256_GCM,data:UedlSPOlOb1frfsa2uSPMI1CPuJ2t1o8C4MV8H+3l6+2bm+FIyMu6Lt1KCesEV3daSltdbNv8FE/Evv82bv+T1F8sysKYxfj/92M8ejxWg1+rrBYBUk8XBTLOjVSxAxZ2Y9uR5laqAGgwUYsBtsEaeIBJq4yQlhVA8d1ERz/iZY=,iv:QlcTF/OdGmiP19v8gQWpJOT22IJ//WN+QrtsdHhnhTM=,tag:ikxAWdcVuWSoaA34wirkiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
