apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: guava-tunnel-dns
  namespace: guava
spec:
  endpoints:
    - dnsName: app.guavasuite.com
      recordType: CNAME
      targets:
        - "b70d130a-1e01-4ab6-86e4-5043c61cfe0c.cfargotunnel.com"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
