---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: guava
spec:
  encryptedData:
    .dockerconfigjson: AgA+AU7RTRZIcJMn5/+62qqyy1iGMooLEpgLDurP1GBXdGngNFnw3+T/zXds9aIjw6DR4sdcT4weLyhPoSdrmW9r3htB5BPH5eLjAnII9OQ8s3e1fYX3FQdSHYemcfZ88W5Ykq4B2Ttu+PvhN63Ji3ETMe5tdfTBtpYpwT3EL0jdZZXwfL8rjD90ruSDZxO4qlK3ILhh+kWMa0nLhG/l/wUXyjScnvSKTcsvRkBrUmbZChpLe4Nj1jkokBHeaKdq4IC8Yx9Zsr5Q2briAJVH9NdeU8apPDn4aEGrjeJl04YfQxGj+aHaXnTHhdEc3qIQ3fK7h1OZcBb/Cpmchr/dv3+RYrh0iIw0QiRcIm9/e91z9e2Etc6bmDJu4zWioeX/cEyvqDs7fs/u4UP/xV4Xw8GKJJ3BYXVYs199wSmviRaBdf3MT5iylJaw795JT08IhciY3xwEgERYjUaeERpYflV76q1KdeEulgE1aok1G2mmbSARdgdb0y1phSC6Eqy7veFO9QMeyOLmosQMDpiXvVU7p8+sPqKcmOdfeDGQjkP+ubbFMHD97BLz3BqfFSz03BMrhVILvoDsDDmepmX5GdzXrmARP7o2/nQSDAdrKdlvejfYyZeXL/WhY+wsZD8zF+coFJ8D5Cr2kx3RMe//1ShtDXiNVgLvrEI3ARUuyiOQc/31oKzgp4yoHUQghMRyh1vPUQ3LwaMfRKJqMdBlkfZiy1PTQRUSdIuaxdSL18MDbyzQxt8BFXt+FrP0gPAwjB564C6IIjG6lmMRMoHf8C62nVWFFFGyEJ2lfACJj5hLtgYssRl+jkRSfPyHnEG1EAO8kzHt4fCKLWdxYrt9w7R8hrolMVADReMujN/mC4hSCuHdB2Qgh/934NQPzWXXpONjBgXyD7zZfku9re399LwIjL7YIhmj0AJYQyy3HWjDpnI=
  template:
    metadata:
      name: ghcr-creds
      namespace: guava
    type: kubernetes.io/dockerconfigjson
