apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server.yaml
  - solver.yaml
  - ingress.yaml
  - secrets-sealed.yaml
  - ghcr-creds-sealed.yaml
  - cloudflared.yaml
  - dns-endpoint.yaml
  - cloudflared-token-sealed.yaml

images:
  - name: ghcr.io/mmeinzer/guava
    newTag: latest
  - name: ghcr.io/mmeinzer/guava-solver
    newTag: latest
