apiVersion: ENC[AES256_GCM,data:3EI=,iv:QnKXiNzR5y9k62WmdIZu0o/F/W/cFuaA519zmqrHGEU=,tag:daq8ekskjwKKWy+CeB6XWg==,type:str]
kind: ENC[AES256_GCM,data:wlSMrphf,iv:yt1um+RcBMGpo6x2xMUhYW2VsjE0dl3QyBSyp+KU+oM=,tag:Dhs/EauvAZixdc6f5XP4Lg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:srNBpckt4gPc6hCaGsc=,iv:yHzOwylOO4bT/XCFDk8iqUG9EL4O5h9HcF4l12gmmmg=,tag:KIaN2HSNNwc6ZBrnaClhMA==,type:str]
    namespace: ENC[AES256_GCM,data:Flg923g=,iv:ljxwkn6xboDwVs/erdBQVkoX0acx+UhzZ/yMsf9mJXs=,tag:wfPjlHkagHfx8tZSPGOmfw==,type:str]
type: ENC[AES256_GCM,data:2aH/KucR,iv:XmlN3NU0uc8aVPUGVsiQBc1eLXZrY4KlrOzx8un9/7k=,tag:ApKJ2i50DjXqmcJ/aQp4dg==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:SOqwLVdFq/+0Drm9Sa747Vnpz1kjHcGGS0ZV2KGxV3U=,iv:LFqRPIvHR4QKS/T3FouasHjgbEsPQ73D5wohaO99h4k=,tag:gxCbOZPlIMO7YjMY0YG9Vw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:saGmrK5IzLIWH/RTsHJqZlueOh8qC9yB2ceWSOCDDr2vsXWPB5FoClNo7yQSjqbQFNJiivPAI6nbl2N1SxzZiw==,iv:VJgPRtOD4fZgukfFuUgmTlviUC0031csYi5g5iVEdkw=,tag:52ScJT7Moq32jCnDXz4rIQ==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VjhoL3BoRzFhVHZjaUxP
            T0Y3a0UzV2JOS09xUTMvM2lFNE9LK21lQWg4CkcwaGpoS28zQlpna0xvQVdrb3BN
            VTZ3Y3AzMEZ1VWNQQlJDeXlLVGcxSFEKLS0tIDFucjhsdlVPd3c1dUo2dDV5b2sw
            OFY3blVGQWE4OWZGLzZzVVZwTDVMZVkKF1s9tbO2VYVCTdhLC9a+hsT8WyAN38fn
            vQ7j46SbZh17reswCZUhfuZojyJgbUwoethXJrdPdU6wLA1nHCzlcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T23:27:14Z"
    mac: ENC[AES256_GCM,data:qc+ui2D0Fo39hDTgW1mtEzkQuzHuOTHSRq5SAoqF6mY2WdqxMMnMj+foyznblEASz8abP0h4I/lbHXZ+lv6qkck9D2fR3kjYC86YIPZy/xNxsU1mluEgxCIirZ/3NvDkv4mmPVyujtnKaYge0ckPiNJG6oD5/kdsnq9sXMCCgtQ=,iv:TVXWnua14mvGP1B4W4EvMy8abuyMK8GvUKRxtphS4wA=,tag:wer2d1FSUGDNazJ4Mmj8bQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
