apiVersion: ENC[AES256_GCM,data:8iI=,iv:qMv+TJjMRjKQs5okDl+8XwKvQV+qctQrcN3xc/5gIas=,tag:/11vJu+3DVtZglNxgC3HDA==,type:str]
kind: ENC[AES256_GCM,data:3u2ckFyd,iv:E21Dooo+0Oh0Cxjl+qPMTaNj6PGSPLeURtrzc58FeiU=,tag:5MsGQC/sxuCZP4HTGXDw0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cPCxRG7ss5NYbMEauvRUnl11zDsAWQ==,iv:FVsMVrdRQbb574r6edm3f6fTJuImsvIw8B6NsDSADWU=,tag:/8x18rUIrDwUdGtHkswiyw==,type:str]
    namespace: ENC[AES256_GCM,data:2NIsmKs=,iv:CbN6KSTmRjnrpIduu3HM1y7dglU0zq467cKTeDyYw1c=,tag:HHEIn/+nBj1Yqj/zA0LDNQ==,type:str]
type: ENC[AES256_GCM,data:t0I41zGl,iv:fhLaKaIrU2FMl+hzGJUjdzlJkQmQcaMDwCUfPkiFjas=,tag:VJW6jTisdWN7J0c//iSDYQ==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:jIrH8nOp1Z0E3dpCXJUqdAOtwrmMseo/BXGH0xTCnQk=,iv:A8xY+fAGAtK80w09vqxIyHSp7kNbkavSTvS6BpxU/Yc=,tag:bPqne8zhBmT+IXhysfqQuA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:IhtJN7iIJ0wrnMSyrDFvzroNDT56yF8c5+BmYbBACRzpgeEb7llsfr2EI7T4gY0TNXmFWyXnliIQNjwCxMoF9w==,iv:qVJ7kLZVI5BBy43TwJep8ioxvNGaHu5dcmcAkRnaPq8=,tag:dViafw2mWBqCu9+B4MHhqg==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSlZjbXhzZHVoZmtCMjNN
            cnE1RE9QRCtmM0Y5S0c4emVuT0JFaTZOcjJrClg2N3hFUVZRb2Zia05XWEp3cklD
            MU9zcnp2OGdsMUFOUHNjTWZZZUtOYUEKLS0tIGNkQTdNaHhXeFdKbDlxRHZGVlBN
            WTh4Zm54OU1XM3hJSFM2S01aRXFDM1UKqZlwu+6HDW+NC/ssw+FD+buISCFgKO2E
            7tnpogAZpQ5rB0Nw2gTW4IhmPV1xbfJCSwEipSwijzZctK8JcH0RbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T01:00:03Z"
    mac: ENC[AES256_GCM,data:Y+A9zc0+uAqrMq8V9IWhvWJCxH0AGBLeQkt67t4Zl3S5ajM4BUWvF4k02pPFobUKEbatzqocbZ0UalB+DZIcZIoXbrAmcyare4gTyaskw4H2HjwaUoxW/0E158NxqQJ2Dx0eS6z2OIk9rB9iUSDsn7qdckW53/MNn0ywmm4J1Wo=,iv:3/iXrqxn31tTzJdmuR5XuVoGL5BowlnG4TtO+edeK+g=,tag:5A8Frvjb/+ijWRCG7KfhYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
