---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guava-secrets
  namespace: guava
spec:
  encryptedData:
    database-url: AgCcUvTBCtbHBtFw9sanENXfwpX2rzZEvGj6pCKgqTIdaSr7927b5A3cvpBmozG/I6lbmpT/cJFIy+Mchtv/xcb0+DyP/3bw2eic3cDrBX9slkFfCl5agg41NeP4Shrxxd9i7LUJtIlwXNL9t83mH2SjQrrLZa7IwGqGOGp4CkireoimxFDDw/pGhK7+XvDvK8sRPFEBWD4wv9v4GcvAkwKrc97vXrgc1VH7Bf2ig6vbZIHWAdJ4ZgFW4sF+7FOzG4DmRQlvHM6CZ85JMHrcA8BBWiMRvC1ArA1hQS7JfIEOqu3zp/Hn0JcqY/Z8Glf7rfUHdShjcrw2tENy+F8GF7Ni7AFLA/dT5U9pq7A0U4ZCENsw18JkBmvH3eOtlbW7iFJp/LrzssCU1An7ZLQGXL/rPMi8cGTElcbPZMPNA7t4l+03wuXxqQ7tmO9g7mHfjdvRVKIFVELGE28VFIDaBBIYWL4Jc+/w58be0mVMb268XfczTSoIzku+wSBe0bv81CK3GP6Ss+4dv8GXYmzB2eKvmv74fqofmOVHXnw9REckl6xnqz5n/ELCPh3nRrwCjd29yaFV3zVUMSM9VNb+dheCA4CbMpPdcCQDyfksVoqFYfRZq7hjf4JKK/2LZNX4BBSmTSSHjNW3XKts7t/fotBTSa2jSwtOeMsRFWCO4AuX976vylANXLmF3weG9Ixtz6WDs0QjKf22uL2X6OFFhPrKyVUR0cCjpXpmIxz/cqQsSeRzPuLNCpvCHO05TLXiTYPE8wDQX1QB+m5ZBmhU4A==
  template:
    metadata:
      name: guava-secrets
      namespace: guava
    type: Opaque
