apiVersion: ENC[AES256_GCM,data:930=,iv:RqOhtkLX2AGXwi9jcLdyePHgzdvuHJpcD5yyUgCxFdo=,tag:Lpe8RC+m1NnoTC1yvY/haA==,type:str]
kind: ENC[AES256_GCM,data:TJSS8SvH,iv:X49TasP9r6eBPbM2WkeFeVaamjI2v80ryu0PKL1Z5Xc=,tag:QezHuMOM2JV23GEjlUOxAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Kr3mRiibvT7TZ4OTCHC3oQ==,iv:+IWt4yo2sXkfoEJYtfCiaRc9M1p4e295z2sYRjHxCX0=,tag:36BvdPrByV5NFpBmP08POg==,type:str]
    namespace: ENC[AES256_GCM,data:6HOF6Po=,iv:OTb0NiDD89wuM4nc2unF8ToCJ2HTuqGjU6mIoFDBhEo=,tag:ywsRthqQC+A+qWVhXj9aCQ==,type:str]
type: ENC[AES256_GCM,data:A77NJ0YA,iv:C0JQr+Bt+9D+eJjRWQO3QX4EbWq9xMMq0NYdm/Fg4PM=,tag:JYspHBsnA4wfXL9p2QqU+w==,type:str]
stringData:
    smtp-password: ENC[AES256_GCM,data:Rb4VxUXA6kERuuVTQeKvJf+IYTnUqPlNiFCTCmC63foALcRS,iv:OK54+USswlzEdvQnEU9h2IgO7qsmOmpK311DpFaL2C0=,tag:z6PbLvTr5zREfL/1xS+h6A==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQjQzNEJzT3R6SWJsVjFt
            eGsvTEN6T0Y2Y0drcmp0aWlxTTNCZ1pRQnhvCm9ZNzhzRlZrenNnbWlUUUs1d3dt
            bWdjOVQ1VzlvWUl3STZsYnlpRnArUG8KLS0tIGRuTVdlb2dCUzUxbXpKVnRnT1Y2
            eHlSVUJNUFB2T3ZuMGpMMk02YlErdVkKAjovmDBptrb5Bs1nuPx++AqjGlA3bt9V
            2jvR8yaTFdkTr770YIcoWGnADHsjHDNCMUA+tH9SEQcax1YyuWxM6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T05:27:43Z"
    mac: ENC[AES256_GCM,data:+8scibVJJnKpbcAFJc75rkeGsd4aUQFBySwBL6aGfAAV065aRtu/DBskW2fuuqROuc2xOFKdRqXisjZbS2dlIWm7UEAw1Qe0KRtdToDGN2Y+D0GeoP+1KqORFnvVpFwjXeu2998YVQsg9BMDHJ2df3awwXrR1QuHopnPY1/dzZ8=,iv:Cafyu2qMBZW0PWFma7ZG2Qnb93voMQ1hHRRrVQrCfV8=,tag:vSIE+oxNBSxda8nAM9BrZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
