apiVersion: ENC[AES256_GCM,data:lmI=,iv:W6ao/X0jtsq+/Eg5KgUai2WB2arUQIYybBR8iP/eaYE=,tag:f7dQJPwe69omrL6v/rWXVQ==,type:str]
data:
    jwt-secret: ENC[AES256_GCM,data:o86l05Q+ob/Jwx5+qJPUHw2UsAzzhxUxi+kILWH2kg8nTMIP6zt/qmj02zEO7jFivj+fzi2Y4SUagPuG2wHrUryPNdl4UyDZz/4ubIdfOhF1zS/uG38wu9W0Y4i3npglNyxPTX6ZsqrTCEBxRViVO/BTSTAGfUPI/LzTlJX8V7ktXvCma1x1KgxYd3Wzq2MIU5Jrwyuq4QvEb3wtp1tZZv10GXqCv1mVDATJjQ==,iv:hWh9pofsRNeYFean8G0o8/3QHuo/qCn2cXma+fz4UDw=,tag:HWxcjK1lWjVO49jMeHySig==,type:str]
    redis-password: ENC[AES256_GCM,data:EL/3oy8TXs0j35GQs92FaypZHYfbdrHRcEHz/NREDT7ZhD5cuDnN0lx3nXc=,iv:NIWkqSMYTR3S3V2oX/Tvi0nThrLUIKTYenHvXwKxKEY=,tag:b5VSOvO53N1Mzcg+qgIB+w==,type:str]
    session-secret: ENC[AES256_GCM,data:XruNm/Ia/HJWCZGMTce+xcC+VXvRVF5sVySSJi9nJGNTtNC/avoKXKJQHNQOwiyv1PxAroV+HJUtb4UwARVll0fVBUzwVAsRi4bBt1/i8dtWR84Ouj/6im9P9BYweU+tywFafu0SzTP0uDu+RAqGyfUOA5MVk+h7n9Kn2DUHrsr0Cmvi/d5KyFiqDoB/kbK4y4b9iZpmxgw00cfdNcD06ZtvxSpVV51z1FznZw==,iv:9aMGTidzVXPcyDH1BKw9GwYRxN6t53RcMqIZYKEzRk8=,tag:Y9fcRIyftfGzcrhEce+BEg==,type:str]
    storage-encryption-key: ENC[AES256_GCM,data:UQrVSuhJ+9dlsQxDH1MjlVuHrdOw98f1eyezi4/qtlKNK+Z3F7RJLVOa9AmZAqhbiLyBPL9GHHocyz1qU+nT9dirKDic8UouMpgMA80B9lkQCzsubqoxjLwNK+Xn4bpDMN9kk2s6fR8uUyrw62kij+5RjGS2CGdEXDG2T43oZQ0IFimbP/s4EfhWP78r4w1Ndbd+flKuoV06csW6qDsXX5pN0gqoDjD56yvWIw==,iv:DaZbRHCTDxVQg0Np8YyF2kP5OaCWwO9dwp49uqrp65E=,tag:RxSRwFfFTme2gMbf/M22Bg==,type:str]
    users.yaml: ENC[AES256_GCM,data:P+Cz9Jw7/sypQaMX1DouXM9QlMtMS6hbTfYOs3AXeJPBYhASzw7OVLYLBzSyZxipvpa5Qumy65hjFc/ckz67A9I8pg7yUZtHWZ2bCfKvaCmntBLjgJkdF1bwhdP76PB9+E6WQicBifH4NwmgkrHYIOaQ1m6LG7kH4nalkC0OgcjtUFbJ4FrD/7Ks2oNH96CF8gOo5+B3IxSEd9PVEniLZBSKrzmey4CM/wCQZf2c2Dotxb05AvG7yrXaKLz2COO7Z0RzyAKUjIhQA4J4hI9Ss5rLKfu8sq+dJBadYRArOCowoXjVfbbd0+hf7CH6WZpN,iv:sgzTLpo7XMtREvDzZcAaBl8SQrfHCYNakEgMUDiScL0=,tag:o/ebElQTB7TQjEs2SXQqGQ==,type:str]
kind: ENC[AES256_GCM,data:kMOqS6aw,iv:mbPkQ06kHgqHQGRn1G75VqeYceHF1nkuSaXypNCLnQI=,tag:xohMsZQHFtZc7X8jH2BQeQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3POTCvFoK/Y8Q302ynjJzw==,iv:OWFkFnPAYE6TcTdK8SPRsRI+m+HXjz9h3rHcN9/eGbg=,tag:V6knwKEEko6JxtLigTxoKw==,type:str]
    namespace: ENC[AES256_GCM,data:Mg9ATh+hezI=,iv:eg9fyFNZezMqB79E9jJG7jbYvr+m/SCcPQN1SRp0H+I=,tag:wB2V1UeZ1YmhteEPaET5Pg==,type:str]
type: ENC[AES256_GCM,data:3ctHzG9h,iv:qkHWN9hZWS9IGMdN1xvOFIi2SwIp8c463Ou+m4fZttQ=,tag:2DjTKTxrTL81zonJ5NR1Bw==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTnJ2Z1k2UEdSdTlDZkpu
            dmVBUzkwT2ZOOFhNZDZIbmlhMm51R0xvNnpRClJlTVZ4N3loMnNsM0NlQXZNc2tv
            QUZLRXVzbHB4QkhWeFdEVHFhVXJaOVUKLS0tIFY1TUFnbi9DMzViR3J5Y1B6cFhE
            dWlOMUcxWi84VmU4RjhJSGJCWVJYdnMKvWJC0Z5c1TfjEcZuJF29MSllMdPN43o0
            KJVMqT5Qz4je8wklcm6t412rFI07o4QHpUbtdXPVOO9qXuNsYzfQMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T05:35:17Z"
    mac: ENC[AES256_GCM,data:JfBKMGK9oqXgN4y/GsnFEz/r6vJ6s9UmGP7Ze54gs5jWTNq3yvqkHjYu5hS7D6yv3T//hSpRacAbTiQlcSgWcUSRTBga4da4WKLJPASB66cOZ/NdUUVrH9XVYZ5VcuFjk1DfUdHJeJi1VwAD/RH4jkrj3OyhxTg+ijntploU9ug=,iv:DPg3lsr2kVwdvp3xqmCAQYf7esfjF+ANhydFtzfl0p4=,tag:Id03rjbPFCgrD4qOiFpNxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
