apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 11.15.0
    helm:
      releaseName: blackbox-exporter
      valuesObject:
        fullnameOverride: blackbox-exporter

        config:
          modules:
            http_2xx:
              prober: http
              timeout: 10s
              http:
                valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
                valid_status_codes: [200]
                follow_redirects: true
                preferred_ip_protocol: ip4

        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
