---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    admin-password: AgAYVWrh/zylzDR2Wgb4XT+ybo8xI/aDeNZKN1sw+C/yiCptuDiZpZAq9i6aGqhvpDtIjwfZBdzEbQUMXN9t2G2uuriwLYicmMcB0y6UaXUplJ8V0QDuSiAUUSnVrgSEFTQV1nnzbhXSfX2l+6NCEQDZKgtyVjBV8g0iABBUzO2kidUYvzv4V0smI5/bjsaJV6rENg75owlpSdmnBtXauc90T8kwzbjJavkxivNZ49Uf+xPiFzDludEMwtMIcAa2TwBs9mYnelzfVIbgFgQF41HvtEVDtNWtuGowJRR/BXIQi2oKsN5rSO0jSXhXlvqiGN1BPGHPLAcVGz2odY46sBUhc07iDzmUMEmH29yvjApxry/dxKUE5I7wwcN10HwTSx04UTzA9tPHfWoZ8fJ5/65y/jldbkt+p2V806/1xUKqYbw6sa1DkZcX/qEMGJgo2JH7Q7RngSSHwyyUAvnmAcoABZyDy1l1ZhjukUPCdpwiTvGcurhIWp5gukEAMBbbtJp/8Umw5EO6rQn4sj8xQaplRZH8SVWxc4JdT4WhGF3dvGRySzJDsRtTUE4B4L7LyeSb+Y5fkAf9UMrCOLNuPoCshxOzFCEeu9az44FN3BzjNV4QWOKl4jTiUoijDvg5DP7+Zp2JvmSAO731Kq3q645AdVahJaffGNhOr8/zuEqY9mOXJD07FbjBzTrYFePdZenxHPCECZPzGhNYHLY=
  template:
    metadata:
      name: grafana-admin
      namespace: observability
      annotations:
        argocd.argoproj.io/sync-wave: "0"
