---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    admin-password: AgBvHQzOtMG/IegrIIXHEEoolCFGUwfbf95X80HOKrFjpr79lb9m73ajk22v10d6Uq8XpO0sDiZ1dsKPSPV4oje256Vgwu/rlNDbRAmA4IvdCIcZlV/crZo+Osi3Jk7lmg72DAt9eR8kE0oCIuRmBwhz9owtL2LWuo2QSktqayOcqpCddEMM3DmvEpKsVz3LlHAmIBKG5r6HFps6VG6KuMNRBqKz1kzdaUxJ38x1Z7VpjM8WzbQyMXD6Vd/0F5gjpy8+ugI27c9h7rx7cAD3Z5IKiey/d0AysVu8oRsvyo5nKTMtdRuNH8hcBJM6h7ehKH1ws0QVEU0hLpY6w76nM/O7BAbS2j+Vldh1uUh6nFPxONDW1a5o1CqoEL8a1qpZjoaeYUtYGWe+tW6GVZxVzDZF56Rv5LaNGDVyQNRT5GELa5xqqLpfIjqGpiKZJkLKeMZxQGNFd8LPjDnRSgI9oNLUSsokqFWLs730Cdq0GFtKKHYYHSgzqIsmndeYlQUlNkUpjYC/DXGoWliOutXcoQOAwr/5yb6sXOJJxKPZhELbDRvkY98N+gcfPoo/mJBveoQwNz94BMudUVani0veqWKWrDVsrR0p5wLvS7E86GWED5+mpTzGV4EKyaS9+hxhIVWIx6vvDH7Nk2auzv8OL/SY8jo7pAe6IDyL+1XL6cimDevcex6fjVTnNfVtNxCSKqZrR1nci68ecf92vdw=
  template:
    metadata:
      name: grafana-admin
      namespace: observability
      annotations:
        argocd.argoproj.io/sync-wave: "0"
