{
 "title": "Guava",
 "tags": [ "guava" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(guava_rpc_requests_total{code!=\"ok\"}[5m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(guava_rpc_duration_seconds_bucket[5m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(guava_rpc_requests_total[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}