---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: r2-credentials
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    access_key_id: AgBeUOd7uKJC47YySb8jFHra2q+kfKNv6x8qAhE4BoANtVX1VD97yIcEJgWszWBSTfxYwXweIogkfVteZmu+sJG+gLp6or2BG/JJqIPecvTnQ+9zNULTqSEafiGBgC17+MfEy4bpTHUuahwN8OaMYE/zQLX8ko8P/wa63Vy1aC07LYgHsBNmptfLFguy8DNr41XjqgcP29FRdgZ8w+mVm3/k0zfewa9+p6+5p6Qe6fWdvudFlH6H1n6C54Wd6oOPWokycYmDrfnl+8JNxuyzqC8PR56EDZyLeXMGiSBQzxTGjgzWu+j+o7Tar2BuWNFYgwL2fV2nn/lH9RYxe9WXEq7hPdekyQ9FMwsdcpuZn+amm6yPzOcQ5lEPMyNtS+73RsOfZKG0AVgl/AGrgf8/pBT0M7mHe/HSW6yWDYk0bmdXkzyL32qNfoh95p9sh1MdU02+amLrLzWAhn9UYZ2fmYcNRTSJ9EnAWSmzX7y0vurqiuOet+KSVZHRfJXxooH7RfJBm17v5V2u01zFnLhI4xvwHlOOODRrVIUB/1HsVHnWAUIeKPnxL1o2thGtsJgxXtKmwrMl3OlILiYdnbywlaaGk6XPynsEqm7BF3FaBu6csHQBU9DeujlapGjUQISfIdm7rd9jHsfS29xnvR4a4+yg6NxiRk2ocOvt70BYIftfiW6rLrSi+qKY5IgokU8oinX78i4ZSh5o3rjlrIlDeaPCYdCoaFwgC14C2S7W06By2w==
    secret_access_key: AgA4dKZYtbAS8yAuAENkiuXtldbKFhNPzbGtXquAhNzJf7rewnOlxKUnFEWTQcP1cTl/tOvhCwSarZAlzSFNIV8Yn7ZWlF2CTdab7D9Nu/n9MxypRDVeUjK/01pxX8QSP7lYtViCnaJ5IIGjD/uUSk6gZyw31sGIvDrcQ025cz+eWSjjlNY3vkxwpSJZ78lIv8rvVt0YMDZz28Ndcb/tKpi+C5txngB6RHlXbprhY8E1tdCx9AdXKTRiTIwz9JGi0fiULaDmIbBCqilYZOl8/yv8Is8od0xgKE4Ixmx0jnP+LhgLZ28GQuLVrTXyBbPSe9PNZsAxRFA7IiUiBYrOYnOPs4Qw6d0G2XCb1Mbq/tvHlSqPaZdXWO3UI+3s3o2uvL3bkSLVy1QBejX4FY8IAiQ9xXFhfwJbwpWVNNhYb8xAXDL+eL1MeRARS7U5bSb5SjAqPZUHglw2lhUqFfEoLE2xkUIaaFjpn6gY+9GvsEM3mLadzpSSsSCtDzBnOOLQWYyTYCCJnfl+TLFZ64RnwE5rkpCiZQwO/zk+5F0t5dWscwA4YzZq3uIJ2R729wcsdV2dwd0WskdhDTMgoZHroYXedfn8NEDVY2YFdRrMJKXdHwyNNNr+WjDGClnFigGgLmOQ7o92eHa9pG9erBU8BLjtCHEsGYOABaWefRhI3AgC/GgEDQKdrQg8jMlDXd1X+a5IsMAhDuG8te9H3q0wdjw9AjBEEXPCtsdxgLdIJsluGVdh/rejn3ELdayiix+DRMIApB4LZu5jvY498tNy9wUV
  template:
    metadata:
      name: r2-credentials
      namespace: observability
      annotations:
        argocd.argoproj.io/sync-wave: "0"
