apiVersion: ENC[AES256_GCM,data:iTc=,iv:u88IKCUXTwWt2kP6PfuJIkb2hEhPBn13u30Ww6MN1rk=,tag:Mtp6j8M3mh9H7xxpNi94UA==,type:str]
data:
    api-token: ENC[AES256_GCM,data:eejRiAiil+mWR8jFRQLlK951EwVOOt1pLt4QAKkS2vW9uO6B4M7retUGjS8UiXVz26POFl198rM=,iv:cCOOvyuX5U2Borq+w1PW/49wCiylsoiGQmvE8qLFXcg=,tag:HIIvq1lID/mST6duppCFsg==,type:str]
kind: ENC[AES256_GCM,data:NGDsxmGI,iv:peNAhvt1mop89kynRBTLw87Y4nlF7Qr9csuqUrk0VFY=,tag:Vvl7lXoL8moUw/kHCEss6g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Bq52gYp0qGIZmEKLdkN/ofUateg=,iv:gyDB9Z1N+8WMf9JQ9YbQTlSszl/stDKBUhXCtig3G9I=,tag:Xxio5k7a7X/QRynEdZTakw==,type:str]
    namespace: ENC[AES256_GCM,data:tajFjT85BLo4yRSw,iv:FlCa/OY6PLpi5M2PgV40QVzf+N0tc+hu5AKM0fTLpTA=,tag:mys/IcU3WY40/9HGAcMIIw==,type:str]
type: ENC[AES256_GCM,data:YYy3bHI+,iv:y97LdFnKiePHXl2BUi7lbr3VD2PJfLy6dGf2gpeDSko=,tag:t4d1ghFzSSkdPBCQxj0EJQ==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVVo2K24zaUtPa01mdkNr
            eHFsS0ovcDdjL0Q1Z0xJRDl4QWNTdjJIbjB3ClczbDZzdnNNbW1mRzFmN3F1ZUpt
            aUFHM3RtSU5oaXdML0RuZGw5dkIxTnMKLS0tIDhFZysyY3NDQlAxTlBVcXFURE9r
            aFp3SXEzK2JUN0w5dmQwVWxBOXQxQkkKZthMmAnXN8EhbFjhKm5BGCiDFobIG5Ee
            ghO/Mhw22yh7vRZnLOh4xE8OcOZd5kvKBhQ8v8Pcze1Vs2Ae+34N5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T05:35:46Z"
    mac: ENC[AES256_GCM,data:1SC7GzUVpdJkig+UqmjS5rG8nzaUAtqmtlAVUlWIcpjVGdULNvQHWscifUccghAB1bgNVnWPflwxGZZl9s+TG5ksuJf1mDj+Uu67XYmNAi5M77oxo3FMfkVd8CJnvEv/1dQajtSZvmVCqHsZ2CadGgQBh0jHDvuzXGjphbubQ/o=,iv:lmrR/mqKNX1CPagGK2IOgO1VqZhpyg/7VWcH2hugd4U=,tag:ZmokzKT+mssWVN4BV16UGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
