---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgCEnZbDc89c5qQ1vdxlmuh4ojscAkL67dJeBxwF1TOW5vr5M8CBdqX1psgpjQo8qY+acbE3MdSoOU4eoDvZ3hxlX3K5dtKGDNjhGZenmwrDFLZotomt12KXKuAI1eehbz1wgwyRlDlexwD20OlZ4CAe5pvf71K/c9sazJOuBRI5SMOXY8ST7jGcVWDF09zDAJYtnU99/BAYLXnQf0UEgWFMYVJjc5Nkd5mxo8UZEEIp+NOeIGdcegxBSlKn6JE3df6uLp1IQt36sdYmfHLHZnh9qiuZAGEnRmBKQjoftIvP2w6F121IEiKtaR0nN30DzOIupqsHZ6X8FB0OCekNkgB6m4egzDYIHXy//dEb3bjzcoOf6aM5y1DdPzggK9VniSOS3r0r1aIr2nJkFRotA1TLOLqOd5rdyuerdQVv2zGLVyF1U7voX87KSMgCdHfVcbdjB+FdZWq2kNj2f7h4aOU0T+1RJ7uFh9+aUTp47HEdI4KYlPVf9um4HXlnXUbYFupIpKa8cvfY/mXZ3agrp392tbwYyT7xCWpe/XBdU5gHQDR/VDbNnToPN+kRM387JBaSlVc78ioX+bmK7u2OJvmMPHYFu6qSQ/QPGkzy+ONciC28NxdNgy6vDZg+RsF+yGGsRC5OOvjE6FKna4FI57NwmETAVt7305kDkh3RJDDe1j3wIBDYKPLwV5NH6wIW4FCig4B4yQn4w4LPNCGiHc8tX1JRN8vsiht3WSjOC9J+gZq8+G17G44pcg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
