---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgAwcx4AB2cNc1RzqEILUVg9EWgGRP3bvglijmjjPmKLaGRvF7C5iCPuoho3iOPqP6Shn+VgVz4jIXAxefG09WtEG0OPgd2Es1ODF7GBvYiZNLuEtCThpZ0hh6DamS7+p5PUOaWsZxntJYC0lbXojavTOmHNm7Ll2Z7pywxqWllRHJevk2LrSEgOy+Y7CyEh+aSxMR05+nZ0uhYsJnf+ylcpgPuV/o+OqJbjtMICaJqIlQNl01t6c8K25X/DSEjX8iS51AchgpTJi1GrFoF4mJC66Ju+O53gDdxruF8uHWmzlkfSXXBsGhm8ZE4GuJUTtFRhXmOncWvAQKNOJeGBsncfyWWy1Ca6P/gYQL+McJAYLPFhAqvXZr4Dyg176GEZIi1XliSd8KsdC+IJq/4wLfIG6XZjx5O4+AtoMGarbcsg1wcasIykktBwjaCgxPk5ZUg/ckXQeaXDTCeUIB5W4UPMIAV3mpkYayBC6o/eDICEYQf7QoxSszabmJ+/tKTlaG0XMsVcel3OtkQJISTyFgNHwySF5mVocH1g7MDmuPjRJuY7m4iRzGRYtK6h7sdnPL3XebTv8ZPJU5ZUgkrAlSHCuOrhMR62AouEc8CNiPbFp/1mkQl3f3Cg6P7IZvSiZ7Z/ZZ0MzRjO59pp10rJVITDwFEIKgV97/EiJdGgq4xjXzovqp4oflG+8NR2ZuAoQymh0QtWnZcMCpvFbo9fgspDiMwCF0uhNSdpzlU2TMWp526B4Zuq4Obn
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
