apiVersion: ENC[AES256_GCM,data:ukY=,iv:koRC0xolWnmFYbafUsw6KDdhCXQ0VBiBcclLUO5/QYc=,tag:y/3Z452AH6r6n6AuEHgdAA==,type:str]
data:
    api-token: ENC[AES256_GCM,data:q9sKe7GiENoXsRi75yrBF5dVwD5epVjs/6R3EId6pHvkhHfV0vGvFOCGZ5FyjRODJXHdbDUN6b0=,iv:WiIXZsNVEx5rHt+qDxNwr2hw9l4eAVFeyAN2tMXuT6A=,tag:lOvO4mIsR03eSyVYz/cC3Q==,type:str]
kind: ENC[AES256_GCM,data:Xa+GPvSQ,iv:XXdfXo71k9mvekO1ScoDvTUa+EjJklM2Dh0y9bapzWg=,tag:cFy805OnPWFyTWtNTjLWMQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ELTCsK3rzWcNQkjUHGpCIBpezG4=,iv:xjklLlG7mMB/16lRUs0XHmvQFgWfl4w/l5H85JlVuf0=,tag:AuUGFB1e/cjgQHkNpPqnuw==,type:str]
    namespace: ENC[AES256_GCM,data:CZUTdJKXX6zGoG5X,iv:NB+hfop1D8rqYLMhvI73x7K+OV3Vd1RmpkR/+QReYZw=,tag:8bwD3MZ9Ib37LiSZsM4ySA==,type:str]
type: ENC[AES256_GCM,data:T+6qYt2n,iv:j6DgfDls6CLH482vFnus6jkIsB7jjltPCWBNLGuZ9Rc=,tag:XuMdhUiaAPhw1EiNZ2svGQ==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQnZabk1qMlgyVlJpUWt4
            Nng0a3ZOY0g5dEs3T3ZLenNwQTY1cmV0QkFvCmVicEhwT1ZyZDZlWjcwVVc5R1RJ
            VWlNWUlyVnlZMDZyRDNhckZURzR0WkUKLS0tIFR5NHU2dWN0WDBIczI0NU9jZGJj
            QVhvSHExN0pWdEgrNXpQcFQzUHJ5alUKCorbm5HQLdcs+Rt4WmFOTROxradldIom
            gRiM1Hpv0jEh+fB9PedJ+mkNbpMrEgY0QHLbqEzKNSb+jESOkokiNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T05:35:49Z"
    mac: ENC[AES256_GCM,data:CA4z5jdiL3lUlIOOwyYw0d1Omq62RLSmTYWiaAsUksbcziLRB/Nba4b7gYiHLzbaQvuD+Nt6tKRldPfsCxWJM+Qql4zVjxuT+PhOGB9AAOks/xwMhExhQ2YOGLNA3bhmBpbd1bT+EyrSfm85S54qMFOy68C3OHZc7wgqUkdqEK4=,iv:ED3lpBMxrcpyHBoCQDVbua8gRBjZwmoddbCEIo9Y3og=,tag:kmXE+K4SC0sXFJhyEJe/DA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
