apiVersion: ENC[AES256_GCM,data:iOM=,iv:6k0DVn3sYP2CvashxLfylCEX4VfEIURNWLQh8yeGODg=,tag:EwmjmDnDyECkajRzilyg2g==,type:str]
data:
    admin.password: ENC[AES256_GCM,data:sxMSa39poBnXqkiX+gJ3KyGNGIM9bw76YcAg9FGawDvBaSqQveiJDALj1DWNfFhSdx1zNa9RiKeOeJ6a2G8sesJjhSFtAMoW5k2OSeNTYPM=,iv:5tCYs/q6qcmqbjItfWCQO6UtqK4fVo9D8BL4Acfj2r0=,tag:fk8hdMPykP4xu671zFN+5Q==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:VzA6JFgUB+dc20nPrD3FER3jZiq47kH0rTLLIA==,iv:V4AzqPOb52etH3kbmwHW+szlh516Hq977Jd13DRBuEs=,tag:G/F74TtvgOxx2WcCrTigsg==,type:str]
    server.secretkey: ENC[AES256_GCM,data:4/kfdX4oKmxwRizhyowatDChm58JPdv9HyECTikkMjdI44vyRGWQE53dNPNn9N2GC1Eg9Pn39xEPo12G,iv:1SOmQ+HoI444t0ax21Djzwu/KT+9ago44Zjj+3BVKls=,tag:RO4VNdBd0s2cpwlWEJYubw==,type:str]
kind: ENC[AES256_GCM,data:aE6E7irc,iv:02SAp5wX79F6S5nJPrDl8XDzXUD2Hu/PloCWZ8jGlsE=,tag:l7ngnF5xXuuGzavVk1FenQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0EaHRrwumpyHzn1HgQ==,iv:miiUoYmFVj2XQwN6Ux1WTUMVlp0+UsXauzD2CxCdY5Q=,tag:4tbkBPIt1f+5QUIIONWUrw==,type:str]
    namespace: ENC[AES256_GCM,data:0Tv0yoIp,iv:bghpVUfC/iP7Mem4fM/jAyYkU7Z9LDX+Nr3uhGRK03Q=,tag:ZaAI48HfdtTum6HD/cG/zg==,type:str]
    ownerReferences:
        - apiVersion: ENC[AES256_GCM,data:dtHWd/doFx00yIF2usJ7Ghy/s0Y=,iv:Xh/pkmllumIDcDvcISmbNCbhrgI0gkx2096AoRyjyoQ=,tag:1g7lBu7DNydSuPU+EPrz1g==,type:str]
          controller: ENC[AES256_GCM,data:ZlSuzw==,iv:gy9aweCy6oLYfbDtAjoiQJyG8KGODnJD9Z2of8Tlkh8=,tag:TExHMXeGeMsVGBrn63XASQ==,type:bool]
          kind: ENC[AES256_GCM,data:rfME+GsQL0RgFqjh,iv:JrJ2dTnadIfnlmTQOEszlNCHtH0+U5qeRw66rM68oPU=,tag:fgqS5FNmNAD3Cz8fZw305g==,type:str]
          name: ENC[AES256_GCM,data:MGypf708sjAkax58vw==,iv:E8Kne+Q9EFEKl+SH0Oz7cclyKv8Tg6WuJ6gM06ovfkg=,tag:nMP81eK6zhVQeECu7xxyGw==,type:str]
          uid: ENC[AES256_GCM,data:E8kd0CDDVHU4xFVKEwrGuygF4VPSSnFHjsNfx2LXALHR1wxX,iv:ctlSsCKCpz0BS4FzoiW/VlmJEqURLdwZAiqWZ2YCCCk=,tag:zI4/mjabs9exm2gJKAQDuA==,type:str]
type: ENC[AES256_GCM,data:hSfm3PvZ,iv:KWAJdyJ3LQeGCINhA0OKXLGr43iovizy0eaeBGsdg78=,tag:VYwEQuWGIormkazEocQJCA==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWnBIMmJCODJIVnhTM2VV
            UUxFVFdHd2I3bnlubEhPNFFWNUZOeVBDVmlRCkRPOFBPMC8wTFJjNzVLcUhHWjM2
            WlY4eisyek1JVzAvNkpDbTBmYWpzcWsKLS0tIFd4UDZqN2pxenZFanBocnJjeHBM
            aWFQaTJJRVBZUmRVRHQ5WUFWbFZxTlUKA1H60Fv5SIEdY+yPyJRzrfCd/J+EJFUt
            whJ/r3A1gz0eK/vACxSAsB8CN2aRTuwLNxo4jP2aOxdP6Yy+dWbTgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T04:13:50Z"
    mac: ENC[AES256_GCM,data:oPI1Zu9wtpAanbvqy0FK3glcKfFKTm4IFFh/HgFgIWK3ZoXlLLNPHRr3JJrOyXolLYmcdK2ILeckrravdOXzhRLoBurmEEwc1GsiF5F4gfhnMNhmLdm72Hh8BJS6wqQDKs0CK0Y21qkt9WP0BuF85CDxwzQGyFaWyoYYxH79Dkw=,iv:M6qEBQ+x9pV5OQPEwo2fKU6PO6nMKm90NPFSjS5THFE=,tag:3sr1uGMcci9mJ3fLtWI75w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
