apiVersion: ENC[AES256_GCM,data:mGo=,iv:MfJmw2P/n2vnkkB7lyxWwnjG3fUNeKnR3FDfnvjEoh0=,tag:QIFrvqLsSnyy8q+ttg56RA==,type:str]
data:
    admin.password: ENC[AES256_GCM,data:HtE4Ss4F4jKw4gZxw/+Q4UspaKd678jWTd5xYMMscZ840rm0H/MZR4SaaWss9d5XYSHH2NX3DskLetsC1AXvyvOExiZlTUGb3Ot5ZY5Dqpk=,iv:BESHQAWpC55FVw8A90pE7D2402Ntsz4KsgMmsUOWLog=,tag:Y1TxpEwYHBvTf1MqCN202Q==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:oi2JUgKAeXDj4OfVpLU6kWM/Sh1B6qHkO2NS4g==,iv:TDrn0fR4fBYBhmnZtKP0mzhhR93ydk4aKtGskPnGWqY=,tag:RV+rSM4WtVnEWfItBPHH0g==,type:str]
    server.secretkey: ENC[AES256_GCM,data:fk+B2Q7OCLQpQb8/E2tX2eQwcbhcp2JeTeCY76Fpi67BxX/x7X1lYF8sl7M/bvJY2D/cvzLeNgsBmzlO,iv:9Tl4z8sYvAZRJ5gebYNxLfUcONF2VtN60jbbphPpPYY=,tag:crDmqSzQJ7f9nbBqN2qjBw==,type:str]
kind: ENC[AES256_GCM,data:bNeSlHGq,iv:eIKpLDLESW0pFOY3t7AQV++DzzR4LxOdPxbpQ09tmrc=,tag:TXK1lCv+ogLSVNfZ5J2aiQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YpG3nq9mkn9wjVlm9Q==,iv:1HKQM6MOnNcaH85+pSRnP//1PPS2LChdE7vqY3yiSWk=,tag:6pFb9fATcG5jpGcEFGnOIw==,type:str]
    namespace: ENC[AES256_GCM,data:hQzk7B/s,iv:SolCs3t1L8M3J+79GgWMsBFDm6wlC7YtZFVEMekEn+I=,tag:kUKNWrvC1/gm06fhcjA+Bw==,type:str]
type: ENC[AES256_GCM,data:hUbmYf+v,iv:uvvgZVULZynjvQm42G8anAURi9EZYj1+/4+arqoq9ak=,tag:v+zHK5dlb5cfNBrRpRDo5w==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbWxFWW1FdU5JVGVYRVEx
            ZkJVQnNndDRUNzNBSjJFQmVVS05nV2hIc1JjCmNiM0ttS1B0b0d2YnZvZ3p6OHlK
            Qnhmb3N5Wm1CU1hHamZnWUFuUGxEM3MKLS0tIFdxZ296TmV5RGZkMmg3bmFLOFVK
            UDM2OWJucllMK0NlZUgrbm9CRVJyYk0KWCXcH6hQ8KStqySszDRXIG/RzUC11Nrh
            nePS1yqIlznczKRnP4FSVA/BhLGV2/oxfubfbS1pRzXqIhC9qCZcfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T05:14:50Z"
    mac: ENC[AES256_GCM,data:chZEYco9BveroPqz7iCpgybuoV2t7Yln0mQVqB3FJt8LbJWvMssXmtdmCaLUJFL/mO6If4s7STl1/X0eMLBZMV2oi+xIWpezWlJsb9JF/4DMhQZ7QXARGDckClSBB4BLCeJISvf78zd1WKe4iTvQ8UbULOhrUFtNHwWnY56e5Z8=,iv:7QTdHN9kvYu5M/BaqUgEYXXyVmshy3DFxwkb+ExCA+k=,tag:oHU7eMnKmDJ6zrYgSqCuOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
