apiVersion: ENC[AES256_GCM,data:QC4=,iv:cYkm/+/Dh7CorCGV6XlvxSnPvnRcePByoeYZp53fhj0=,tag:leuVEA31GKIzSOVSv4zL5g==,type:str]
kind: ENC[AES256_GCM,data:n/X6trRE,iv:brcSbU5XPVQSlhIhGBeyE/eZ5eTNeD2A+R5FlZHFhP0=,tag:Ti4vEc9+swKl0Cu2Nt48yg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pHpfh7h++Qx2KVOzyVdMLtYES7iG88M=,iv:3jLhpjuj9TBu7zqAWXdJcFfQtYn2lESwvoQaDyF3IME=,tag:NgBnsdZsFEeJufUFMsw7cA==,type:str]
    namespace: ENC[AES256_GCM,data:dtw=,iv:4ccFyx71iRdAkHr1Q46wf+AjEQ8o5BiKxXIqmTbqwmk=,tag:T+mmDKlImj7DIgexrhOgyg==,type:str]
type: ENC[AES256_GCM,data:yJOxLHXt,iv:4cOOOAQyNQOJX7HlK/1raIpoV1x6vGjyXQB5JyFq+WQ=,tag:sOJwgmCMUgKAQugUWxAA5w==,type:str]
data:
    credentials.json: ENC[AES256_GCM,data:WSCRZ/MYzrTE7dxDwulSNRveChCzLC2aTn4zkE6NpA73MgfWO7y6T/guXsCnZh7u9P2ByzdOaEy/9eInQekVb4TSJLuUXOjY5cxU6OahwidCwVqTYLnglB/OB7cENt7J31wTIVXpxrIcno+FDpmC1toe7RUfl/3wONFCTX1GaFENOgxwhFtTA+JzMQSK9CSwxvsKCySxcduo9B+5jxMefHqwPOmbda5DyxrsG5rd6lMZXgbuqP/DQk6ZlHGL//YfZjeJq+Ix1IpgbeucYYKYKJRcaVQTIidpAvmZc4k27ppXGTuZHtpQB2miyPg=,iv:GjkrWgGUB+Jbxv2dzljvOV2FlzlxVzla6at6x2t3TGk=,tag:D5+uu0ZlUk/nmGEYznnsZQ==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ1NRWmJaSFVFVHkrVUV0
            bXg0ekhWbWM1UnBOU2VpanVINTMvZk9Ca3lvCndFWExsbVpXbFhTUFh2cVNiYjQx
            K1JVczdaY1JxNkZGVmlVUEhHTS9yVTAKLS0tIEYxVFlRT2dnRlRVb1ZDbTA5QWtw
            SGhCVWJVSXF1dk1NajQyVFpaVzFCY1kKlJ9xhdVzQ0udxn9ldCLLKk7V4ZpLB1Oo
            FMwBI72JFo0JHkFC/Vd06BirAYb8yJNUiqJax4lNPw50s80wFtGT+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T16:34:51Z"
    mac: ENC[AES256_GCM,data:K3c3s14gl1c9nEwdbNBx5FbZirautdFB5PRXFEJpyfrCHpyZMUpEuM/cWTm1CNmSfk1Hc7x42MI7Ouyj3irenQAZHnk0OiGOT+Mby+qcw+chOr5er2gZv4kKE2wo5X24hpE1Umqaf4iNt6KuXDJJFpD0X/c+MjNlQJ4cdat10MU=,iv:rFgR9j5THWuzhaFR/Q54x8TyJDp0OFhSL0+TJKWhOyk=,tag:NWxiek7ka9tN8GY4N1G9sA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
