apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: pm-tunnel-dns
  namespace: pm
spec:
  endpoints:
    - dnsName: pm.guavasuite.com
      recordType: CNAME
      targets:
        - "795303f3-d7a7-40f2-8d80-70e3518f0828.cfargotunnel.com"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
