apiVersion: ENC[AES256_GCM,data:+a4=,iv:wdqBcNAO7B9nZEN/tOL7J2mt89Amlkvw1BBrNWDOyZU=,tag:hPpjDyC4BKj4eaAxr+5D5g==,type:str]
kind: ENC[AES256_GCM,data:BziQvqVe,iv:M86R/9Vma8rypjlczb+bMytfCsHK5CisDoZRnhObA9s=,tag:Mm5BpEnLY+Nc+rkCwcVVMA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KDkD3r3ZuaG2Ew==,iv:hFLP8jiCwlmI8cB8fzAaTWWxLHIHqqpjTFkS8BifbBM=,tag:zm9nZWScHpcb6LlB8CAkGg==,type:str]
    namespace: ENC[AES256_GCM,data:xEM=,iv:YqLqAqEv4e2+HbQKocm2ESqIlCSmvMnydsrk+GjeDBM=,tag:ba7q7Bl+ajzyDEGs/vbRtA==,type:str]
type: ENC[AES256_GCM,data:Q7L/8CWA5+Ovz0XuC9h1tz5wazArHEsOpcagDSlT,iv:j7h7TlEZVZ+MhVmdwhZMD9p9lSJJTAaDOkBesQq5h0g=,tag:aRHPHxh/XRoQ+T9sebIOBg==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:OCUboeYMlYeDSxt+t+yvwxn1om2rSWuQ4e56g4xXCy2hyNJbGt53JRb0/wOQXJVsd32b/yA/v4sHmdR2Q/wHOKkne+dtjkAwZicjfKKbjLUxoABmDDGoCYHZjk1M0LPhYWwey7JXZ42z2F6UxV8iT0aPTTFmEueeGFKRxJqmsjNOaNEYfd413w==,iv:EzePX4GuotWFgSJ7/dfSZq4LLxMG8RKHbsumOO7S0gk=,tag:sxsKwEXT40/esslNbt7Lew==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd3k5djRUd0F6eUZqN1Jh
            ODgzeTZZelQzVzVMbzZaOHNhTjZLOWIveUdVCkVITmZZRUJudHczNjlpRzJyMkUv
            QS9RTHVQa0RzTmczNG5SRlJBaHZCRzQKLS0tIERFOTR6N2hmVDlEeDBLMWwzYytE
            aXpFb1BpUzZTTmVUOUgyNU1GRkZGalUKdRGES8gWyQv0pleImKx+7C1PfNuYW/4Y
            gqbXoPytY2nhHNL3sD1aO7MuMWiUtepPVl9xkUx2+KDO4h6m0VjRTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T16:41:39Z"
    mac: ENC[AES256_GCM,data:JNP68J4l/rb46/KbYrzdbM1HEOR0uOXPnLrTkQbXdLrM/LykvVr5XO2HBKxVI0YSnQgNHr26CWcJt6G0QZKLuUC/uEc5GwoM4Ps0emEZozlH5AJxb9IyD2ihhjHmIsi3qhJujxL26bYtAylTu7Smk/b/6QXstJp7qpUPXWsgX4M=,iv:o3k9ZXxBM8YHiULhY4DTtWV2Ztdd0F9rO2knBZw7XZI=,tag:S9A+3+99+FPUDj7aUMi9Bw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
