apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - server.yaml
  - cloudflared.yaml
  - dns-endpoint.yaml

generators:
  - ksops-generator.yaml

images:
  - name: ghcr.io/mmeinzer/pm
    newTag: latest
