apiVersion: ENC[AES256_GCM,data:7L0=,iv:e0O7FGLAzvyhdBluAqJQ0JPeN1NZWqAGnCsqGdG9jp0=,tag:nKtozMK2Yx1ZyaPPxSHVAw==,type:str]
kind: ENC[AES256_GCM,data:WRdrql9V,iv:JhQmTDWUEnvDfJnzPIHidOdH8/9TFXcchk4IGSrhALk=,tag:UfLcl5fuHbN9suv75UDYyA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ycR4tUHI/QDUxA==,iv:Nzr78RTZ1KRFCIhxbyDMR5Lp14t8079fDM4+kQ79WrU=,tag:z4is2KKWtpEoVEnDHnIr9g==,type:str]
    namespace: ENC[AES256_GCM,data:cpQ=,iv:S6F0uP51IhD/XZ1niBwOLSY18DVeWMDg7qgRng2mfSE=,tag:ZxWn37Cb9u/MFMJ6TYaG+A==,type:str]
type: ENC[AES256_GCM,data:i1f5lBbz,iv:ZGPeQePw1tfx6JgayTQmf1i0GPzia+D6KB190fQU3Vo=,tag:rIJb2S3cJukrzUj/mHHUTA==,type:str]
data:
    google-client-id: ENC[AES256_GCM,data:6AMNEE1LZeiZdqAqZBxKu+V1X97MmSJ78jynHdNEKMpqHIlYVbXc9EDQ8Pc+qPx441UJa3pMfISC0D7ymHvmHOk8f+W4Lu1H6+kn1dqNM+QtsrZPi2X8ECTU43OKuLtk,iv:4eHcYSGsRxa9WmqCsRoUlEZ+4XZ4ti9QOu4HzAvYp4g=,tag:GjIQBzolZOHyB1yP0U9kUg==,type:str]
    google-client-secret: ENC[AES256_GCM,data:LEaI8raYmeXR0UeBOIeiwjuiWKLrs2TeVAcTsz/wcUMT4ygAO8k1YTgAyqXs5vIa,iv:VMbUUQe9u7dbbY2A75zRE0V4cV/ixIayV8Mrcf1xOWs=,tag:GTcn2HQ07Uw5aDSjyNNreA==,type:str]
    slack-bot-token: ENC[AES256_GCM,data:PTmWr1pOmMTLW5h/eFI55o/KkOKCyTGZAAnQ/dMij5OAFVQWLywGXry+XMNiR/FAGDZijdQC71jQ3NPk6BOLmLTPa2ZJe3RBV3OTY+vNkwo=,iv:9L/J56aYu6Htn/UzhoT83RbS1NCtYo5MWkwazF9eQHQ=,tag:KkS/hG88NS1k7IVyqfaUVA==,type:str]
    slack-signing-secret: ENC[AES256_GCM,data:LYBWiqdoGkjIQL9g/4am7enO/v33EcOF4TYG+HSifgEsCenp6r8dM5+vPCM=,iv:FqzVdiOLXurjpc6zjtPs3ismUOdCWwFl8rvpEur933s=,tag:9cnzjlKRjsA+HwlJKe1jHw==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:Dg/jzfSGRlKgVZXdxnZDdqdQV6ph2AQ/nbrAe6ItCYW9tDI0NpuznrDpZX3VsPlvtlpsoKwGy0NmphXPASzYAFvjn9Fq+gUgN9xbW7rCUecBB2cOKngPFesxt5XMkfPVLT8fHA==,iv:FW/0Wshe0NJme9nqMNXw58SS0nE6/5JqOVlSjoF42nI=,tag:w9CSMZTPxXa+dBeXOQVCUQ==,type:str]
    openrouter-model: ENC[AES256_GCM,data:1ktEPgEQqd92UlIPGs4dO0ntfwQ/q0yHzDsTKsuv2KpN3I1Z,iv:5reaQvTaaksrS4ZOuZRKtE11kyx2nfGR/Ae811HyuqA=,tag:HoKsJWMtLuryj3pJmwyVxw==,type:str]
    session-secret: ENC[AES256_GCM,data:xnKcG1HU1Z9a/9SLGmDhc3pqKJwCbVrBR6LlXatu+eydTGQiOWa62pEo3FjQTWF0LJibpTYYkmPNV7K/,iv:sUq/5hzkn74QFIQbJi/mECfLF/KOgvXl9otZOBHKJQw=,tag:e3MzRTUSItbKpaimtFi4EA==,type:str]
    base-url: ENC[AES256_GCM,data:JBd89pSG832ujVYO10vL3ZskS3P+QP8UukvB4tJRZDDABujC,iv:VQ4MpiscLOgGKY/1JHnBXvRMHV/+uWCHmvR5QXlCBV4=,tag:i6bKm6ZyGXmTaUALFeszBg==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT1N0RTkvbFlON0lwOUdy
            NHRYNGZsTlZuUlBZV0QyZHQwV1FheUlIdkVFCmR0ZEJFWE5TbnNURThQRStUZ0dz
            SXAxR3hicXl4Q1dxVkx6dFB6OC9KMm8KLS0tIGh4Rmo0NXJuT0JQRlJMdEhGOU1x
            a2lqRWRtYkdYajlqcHgralJXQld6RlEK8lcgqsOpsd1i70w6XQSmeJxVB1g7yT6z
            uL0sY06wYP67FayP5CN1244woASc71eUEn+1eUjw7frW0ygqYjHZ8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T16:37:22Z"
    mac: ENC[AES256_GCM,data:+Pt8vO1InXAgg7xHbD2Kzs6NMRBnqITwvoPi1QOmVx2pjvYh6DFA0mr9UkjfCF5bKQw05qeheHgQVHny/gRLuxpavrt3lLMhB68Z/cxgIYVXqOzUPMMZB2DNlrxultUSCE2Uyf/yCUYZoMSKhe6vgSyICkcpik5wHkc4KW3PciE=,iv:xbtymShJvaxUh1YNG3hZPqCv/lIDph9d9iD+nacGenA=,tag:njAgVbakEaVF7fJgfApImQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
