apiVersion: v1
kind: ConfigMap
metadata:
  name: act-runner-config
  namespace: forgejo
data:
  config.yaml: |
    log:
      level: info

    runner:
      file: .runner
      capacity: 1
      timeout: 3h
      insecure: false
      fetch_timeout: 5s
      fetch_interval: 2s
      labels:
        - "ubuntu-latest:k8s://node:20-bookworm"
        - "ubuntu-22.04:k8s://node:20-bookworm"

    cache:
      enabled: true
      dir: /data/cache
      host: ""
      port: 0

    container:
      network: ""
      privileged: false
      options: ""
      workdir_parent: /workspace
      valid_volumes: []
      docker_host: ""
      force_pull: false
