apiVersion: ENC[AES256_GCM,data:Z8Q=,iv:ywMLnLrzYR8ivvDvUey5SB4fzAEsbCc0XG9KIQ4SaRA=,tag:rfI+HNEImBMsfBn1PDMr+A==,type:str]
kind: ENC[AES256_GCM,data:WlzZlWcd,iv:+CqM6UfcqqwiztGz3TPXXLwZR1o/fwGNaEC4NY2lmzk=,tag:pNEmzCA+IpLtwAF/a1NJtg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aVLvpBNPfQgvEvStpC+jsg==,iv:SNcdwrrjFmhjEe86tT2SbaTsH/gnYtyqHR5Wbmqd9PU=,tag:MsiCWqHzAPAvVA6jnmloBQ==,type:str]
    namespace: ENC[AES256_GCM,data:SGU3QTA/kw==,iv:WMczalgNZUtN7icpGSGJnB2xxwoGbZcF2+65eHPWePU=,tag:3/1XsivCYNA2YMPROlKsPQ==,type:str]
type: ENC[AES256_GCM,data:iNAJt0Vw,iv:tFi5VuLp9mIznUfWEW+q8FBS5kFrt3w7pXp55ki2fqw=,tag:aJMtq05v7UWkJAbJpfcbjQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:/qIMfC7SquLPaxxk6kovZLZhnoQGtaH97pe5TCrB7nSbim9Ub8c0zpC64A==,iv:X2F21AtCFXxJBvZ3Jfng4Q76y8FfaXCO4y3DaycKIIQ=,tag:hiaSZGRLyBGxVJrjSKW1OQ==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRTduSlJGN0Z6VTArTVlD
            ektuQkNkaktneUNNZmhaVUc5RXBPSWlyWkhzCmJlSjZ2aGhySmJrQ1VtMVpLMFJ3
            TjFBbjdXdTJwRzZDUVJzNjJ3OGRxYVkKLS0tIDIwb1J2Sy84NlhJNGR4Y2ZiN1Ir
            bUpTSkpoTmZUNXVIU2lValEvaThNOXMKyJOZeT+FDibvTgt+tEhm5vz7j5L4Nk5W
            Gmk2V6gPuGf0uwKd0QUgMkUVlw1hmDkUwSnzNG4VCk+LEzG4/e8/Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T04:36:36Z"
    mac: ENC[AES256_GCM,data:JAMlciLxrgzlnXOWzTclhR/mHc9bwSwjvVhmUdfIeSrEzJbt/HXnDUiKSI9CxT+CqJ+dkIFHj4qonxYx8934h5QkLxrsARQojkPukNeqyFwuGSblymTn/07EdTTv9twUtUDEVHN6DgF3fbcs0ASBSzlNucmFnPvTcTVRfc4aOA0=,iv:JDPmILBFi4G+KDlxNTD0J5pg+DL+XDMe55+6P2/lwfA=,tag:PpYmaoNuOqapD73zkTmAqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
