apiVersion: ENC[AES256_GCM,data:ZaY=,iv:x9Ls5o3GAWlRoRoNINCq9GaKkYFxc30VFGWaeRr3zjQ=,tag:N08ZpcrZJJyngkEPuLKcFg==,type:str]
kind: ENC[AES256_GCM,data:QF2zWpNf,iv:Ow5Aev3zM2igs1ocQF/g6VcP+CzOkmFAcdLfmSNGoeg=,tag:L//e6A1UuJgtCFdohFK0/w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IRVoszXNjt1vVpkOJQ==,iv:D1wzP7MMjknveorpnO6CRyS62SosfnZ2c+l8Nt3xMp0=,tag:WnMkrYUFIj+anssRdZHCjA==,type:str]
    namespace: ENC[AES256_GCM,data:+hWfUyBgZw==,iv:lPrx2x1DVu2+U4hGSjm6vJOuBiAJpXwC713nwGl/yNM=,tag:1kwwl/TKLL/WoQ247RfH+Q==,type:str]
type: ENC[AES256_GCM,data:r7j02d2p,iv:D+gLE2196+fum4OaIFROd+R32s/7VmfezVTcd1nxOGQ=,tag:KmXoaGnhMG5jNwoWHU/lHg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:2HSLpd3yA8zjOfgliKOv6pgyrduN1FpnKY0=,iv:fmIVf5RUoUz0XP2a0IZDVsdEmy4sijfcykpbHgfapfk=,tag:Oqf49bWFDhmVKIzTQ8jPjw==,type:str]
    username: ENC[AES256_GCM,data:eqyzMCQ=,iv:wqBeOFYWap8PeSXoV5y0oX3AuhhkaST2U/lhS2yeRBE=,tag:1PUr7SR6duuXv8lZLvk9aw==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TFZ2akxUd1QxTVlaQnBv
            V1ZaWVJsMS9DejVLM0xPOHZwQk0xL25xWFY0CnRDNUlramZjcm5EUnRNSkw1K1NZ
            WUVSRjhaaStOdHZsTktvemM2WGpIY0UKLS0tICt5OWJSbVBtZDZERlN0ZTJIQzlY
            eFRYaVZob2hrNkRkZWZoblNuU3BpSncKK+4rZlkuedkoOqVgnPuqLCRwyafdvvmP
            e1L8+wQwEy6b3gU8qmS6WEUa11e3vtuCgfoCnWW24Tvm3Saii/hMPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T03:25:58Z"
    mac: ENC[AES256_GCM,data:SKIAj5nG+3OCY9prEItriZl2mq1q8fglLJ5fhzvX9AdPkMBifKfDJopVm7ahK6buccoD+HEttAbLTwmefWIE3UMzB9FOAuci4zXAU0TBXY3cGXXrWkJMz3VgEm+R812q260NHp5ssWTwLr46Ecx8FSIbz6vlT1UJKjkzvGImhIs=,iv:HeXktkCXOqzBYi04E0mL/cQ2UfoJqlOnnjO5eatt4NU=,tag:7oNHxOeYPKrqLHRd4aTcZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
