apiVersion: ENC[AES256_GCM,data:H0w=,iv:u36BFvEXVaawKsX2I7MAWcyzcGXQUzf2fdTKAKzNwfA=,tag:TbB5jo2Li8mvnInbYTfwug==,type:str]
kind: ENC[AES256_GCM,data:GTyZdMA6,iv:9YeilrHOTLdc0XmOC+R3v4V1m8zjP+aohljU1pssttw=,tag:1J5XZ6kyfk/YQyK6qj1piQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mN8AozDJw43V5ch/xQ==,iv:cO8ie9URZ/0Z4vZpCBW3h0hcXebe69kOxc1U/3ter1s=,tag:+SAJzpRJ8jegmftO+YJLgA==,type:str]
    namespace: ENC[AES256_GCM,data:MQpNAPyEpw==,iv:G0Hbt1EQaeWgsX7Sw3clTKbOkT2tefTtJOYzu6YCV/g=,tag:LjaZlPBfEZanxIDNyD3kEQ==,type:str]
type: ENC[AES256_GCM,data:CDUBT4Xe,iv:XrBSiA22OnMv4R5NJH0Tpx9o1JWM/bgtIVd1eZDwG/k=,tag:h7eLDRshPt2NTvjjKSTkcg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:GfoyqTMhE0oXN/V6KF2XUl9DxRrgJ49OWqNfhzQh8wg=,iv:pnZhvIT8aNnrrJT1Tmi0dGueu0Ri5EzLxxg+7/C84SM=,tag:kkYxj/xt3YchqoK01+b5sA==,type:str]
    username: ENC[AES256_GCM,data:W84jg8vBBvahKFxV/g==,iv:92cwdY8p2eOmZ5eLNW1pcaCa0Yyx/vZ+BZS07bgA4VU=,tag:6mPVGQk8eVUAoCKOn9xoCQ==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRzBKbVpQbjVNN2lmaXBk
            NGVBaS9OU3VrMDU5aVlVb0VmYVFWb3g2aEZzCjh6dWdUbGhVNHhDeVRUdjFsRDcv
            THNxRU90d2hhcy96R0VibzlObURwcjAKLS0tIGdSYjFwbFltZ3N6MlJuN1RUczFR
            cWs2MFRhRFduemJsdGRlWGo3eGxKN1UKTbkUg0M4YgSNqb5IYjJ13B+j13VDjCh1
            Rt6w2LrQTVWsKNmkBCrvJs9E1i1oUShz53JR4S+LllzIK6f+WkFdJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T04:11:54Z"
    mac: ENC[AES256_GCM,data:gApW0BKVs8yzS9QBmSEs/wNyEyNMAFb8ygfkwlc080X6R4gP2E01St6uRcUr+AxUOe/8yooNdnwBGU2EoQdl7494eMLW5OrvaAq7UYMdVDcswdddP4QTGSnjAt/6lCva4FzdIsw4LyM2JcWSBCRdP/8NScu2AEXo/ZG8GtbWK7I=,iv:BK2VpYStVg3oBdPHugW1Gkws6va7VfIrp3sb+K7PVP8=,tag:+ybAuNgmaSRujtpCCVvSIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
