apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-recurring-jobs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/mmeinzer/homelab.git
    path: infrastructure/longhorn
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
