apiVersion: ENC[AES256_GCM,data:Svc=,iv:Yv/5KA0cG5Gs0HbFimRLfj05R9gSnW2R+gwCBHtlkHM=,tag:3ckcGfcEsvc5WYiQNJCoZg==,type:str]
kind: ENC[AES256_GCM,data:fhyDw8Uz,iv:kUtA3RKZEphzbBLPKMFwciSP19aMyDGaxbgp45bOEqA=,tag:axLIjvxLQdCGL8O4UAhKFg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yH0xd10fEvBuPE2LDxeOvlz9XDPxGw==,iv:norYlkdIqJPmwiOkRoG0+iEE2WTcMdC4wxVs/hvFlk0=,tag:F5OlD+qIXZiTLIXwy2QzkQ==,type:str]
    namespace: ENC[AES256_GCM,data:qEFPTGCk,iv:CZtOA39eqEyxcvFZXxpvdJkR+hg6Crqrkcf5X7D+A+8=,tag:tCWispB8kk7+omHvFy5xhA==,type:str]
type: ENC[AES256_GCM,data:wVE2a8OD,iv:K9PzKAPk8w/5Q3yfMkpWUYpWQc25acLF2kLk0C33kSs=,tag:v/0zN+F8g4RWCqdCx4hqHA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:s7r+GJA=,iv:uCfyiu0TS2KllfEUe0hjMy4i+6Tjb4EMyAgte3oNV30=,tag:+b3LBGErtuHWRdz8YY1Vrg==,type:str]
    password: ENC[AES256_GCM,data:LYtDKDikpIIoAIb9j+kjraXduz3cmCx102Y+WHUR3TzWTfZnVJIqVQ==,iv:9px4EEmepiAhBfH+EdFLd79+JUF6GgAkGLTbdlDQoUM=,tag:6R3MbtiC9DG1tL091oUWrQ==,type:str]
sops:
    age:
        - recipient: age136kj83xssrws40ctd8344uutlh42um2rej0ccvjvws76huynv4rsuqpwse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQm1lcWRtcFY5THVqaW9n
            bEprSWZEc2RSL2M0MEdMMDV2VE55a2kyb3lBClVmaSs3QmlQKzdLZkc4ODlJQyta
            UHJNcU5MVWVrazBELzgzdlFaOEZ5aUEKLS0tIEtvSlZ5ekdYb2FsYmxGR0ZDc0tV
            eHFEUGNidlVHMmlQaGI5TFFJYUd0VU0K/0Sh7c/eqzwtaIi65vCjDmFjNWXZ8GNe
            NaH2JDK3dIPsLk6bXAOXxR8aV4oAlE+0Z7HmKgdrTE7f+OuMFDBZ7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T03:26:04Z"
    mac: ENC[AES256_GCM,data:so9OvaRMfBmlWUfdRV4d5psdsqiYfryj/PzjDqTMIA9ntCIo6zZOw3CHgKiJscU9v3fESndCUSUPtpicLJQU8OkyXRkSqMn2VIttlcFRgx7mjQvFH0s+ECOksoWkKYHDdEcO5Owt/6umnvIp7Ufj6yOsQqGKBtTyA6+2ydgHWTk=,iv:FazNtH4sgizhUcdtKNz1hZiL1O7p/xravTRBBJRaE7s=,tag:+vqq7tlLaDPPzBHusTrsVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
