---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pullsecret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgB13KSKUlXIUhr77GtH8EdRUz/BeX/OhsB7yHERQK8uueFJq1nZ52RuHPC+AVd/mnEaFC58btkvu60XDvFsz8O96OA1wmopS9Pw2WjQ3Q+JqZb46/5RxbfdEEqoR9m/ZPOya0G+0bkGRf46wjRJCqF0vmoG4uVfmXxO0uIoT757wXezYc+0Iw1N9kuzRlMRCZmG/yvO3P0M4BWOnu2kpSuzTDfIpGfEQMryOD89x38mMmeu0G9Kb5WtxfkB235zBrpqHydN+sbQe6AeHP1sz2MSX7KOVQZEcfIM43hWtHThNdvHiieYGGuDTSVC20n40QnlC7SLfSsqT+mbN9UAN4O6nmcajVp0MSCDuYy5W62gYqRAbiyMbrCff5nWjmIBHswr+Ap407gz8as6yffoLijs/q7AnZdv1sLocXhU70gct4h2MHpSLlSAe7XffP1YayO5AKIzKNuZCqj+3FdlJumyb+A290sA788sMvbhnVq6yaXsfQsbVTsHnYHKl63wFfn7+wj9hGamGbMgXPyobSjDxjhFPEMjg6S5MaP/rgjiTzo0+7+s7VHKoDspxm6EreYNh/1AifwlZuOzcrDq3VJhrocUSvcDAI40LnstSTsxMHL20Utol3hepeJ4ckokoto+IyyFTKh4CIhRACq3Q49Wb77hVEhl2ZTBI4hx54UM1I8Uzw7SWxjnc5nI+DK1rN1czQ1e+3KHhHxtZtG4LEMYmrh9qYk4fBRcNzO5ozMd8SbUb3B0HerOMwnofx7vH0v15lKbCTWExzvrPNJsiHt54+qn1T7/CV1iH1r0LM6EEMtDGUfPnP5LxpSTFB9wYXnV/7FmYcbhXdc4WJCzullgx7NAUb9FFsi2zpgvDI0MZSQFJxcqe78tuGejnxUtXZLT8HuQeLX7GE+8RLWuqCOBuZx2RBJJAhgCSPVlACINQr4=
  template:
    metadata:
      name: ghcr-pullsecret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
