---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgBauYiTa0XUKwn+w3upPV+1Ryum1IE7h5KfVLiiGVARektV00qXW9fcsCem4Lty68FBwPfx3STFlp1M7jkFCbvNkti416FpMDDHLC8/2bgLwnoYic/x/k4BNYZvePRtyWE+MxdOKsPlPVpEBb9nr4MI8/3zHuuIAX1vMk1Ml6vC+3Bkq+dFd3f9uiHffaMoNz9nkxmkMSkWvpKUgijEozIwISUn3jxjFH1ogJ/GgXgbMonybretmrvjDrVejIHt858J/pmgGolq+w5DmvXWeCZnehcAdDU1navJQ2YZJLY720Prw/sPMPAer/+Zo4i3SVPgalsZUJC9DDEmvRnQKrWBFK9VcnRRPqTfaMFRPFn1aFCwWTTbsErGdKdIaN2jo5N81dB86H0NBmt60GXJ77Ute1zorEHUO0zHMQBbBXhzEuud2ZO1gaoAQkN/mTrl+mjcTmZw08L2m9pgjtsS3VrUBt0IGs3HK3meplovGCMZaRED0vs0xRPQNWyrY2l+6DV+ouQ1eRe3U9lBCQNFpfvOQahEkYeOU8XOuz5nMwMb2Oz4WnlvOBDe3rscfzLOle/zQ8PNM9IvHYh+1127c08lV64VulNZ2eeksu7/bm8CeRnVmRFHecTbhLxLnqQF+CoQ12GIELZpH1ZWu0rQ5qgUnr689W5uscqUNrpE4rAm0JHK3Asa/U0Ie6KXZA5mEsuHAxWSd+rQeMTecs2JmXfyUf+xiXiQMHj3xKIrQ1Pk4uLPb97/Bsws
    username: AgBGxXAftu/SypUpLolC60Wure6PYypswTCrt5CtM5/WOGN5Zl5800vaR2A4m2G3PmXmc8yC2bE7EG1Jxb2WXsSZ/329NnZiEQ1heRbW/hlaG01ZbbRHnBTWISnj9qoyI+B6ZLai3ia9e2IFdDC4pVZSshqoJjGLR4Ar2ZYXNZSEvRb374bCM4/1QyoWSFFEQzHLBMXGXYxqutpgFgRpyt3uNwcMHw00khcPXvnw/cLe7t1zD5pl75DyWaEWsgj9AtAPXgLG3voo7IdGPVWCy3b51wt78/fYqREPZOMfLI87kOxFy5ZP5S0MQ4MOI0KpoWk5SgijPFiKMSYk22Hh0e6ZzTK1Fy7g6MJMQ/Ab4oBO4cT1jIKkZvKqo/jpgex2cU+j1jJ0RcK/WMXYt9zRkR5VX3hMA0gwUdXh47AUlnv8KuOfJZ6vaQ2GRByAAI5s/NxMdmsSlRcDgoSLV8A4fyQkNu/MYZzAm3tjmKkt1kbIgTFz1k/k42jAOqFSMLUVpsiWxCEsNfP33p8xt4odUsUfVb6TektGdCimGlGCkDzHlsuISsJEOtup6Oiw1ZJuHB0Lv4V4OvlldQfwGq9hC2urz30aFgTKr9GaM35EhRWwq5tE4t885sMPjRaDMjZzF6PigzIQKVAdxbkv/G5Ypydgpcgtg+QS54kCK4OV9SAp44Kl6W1In4QZLi1emaBKc2/WZ1+tbeTG+g==
  template:
    metadata:
      name: ghcr-creds
      namespace: argocd
