apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: guava
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: newest-build
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: "guava"
      images:
        - alias: server
          imageName: ghcr.io/mmeinzer/guava:latest
          commonUpdateSettings:
            pullSecret: pullsecret:argocd/ghcr-pullsecret
        - alias: solver
          imageName: ghcr.io/mmeinzer/guava-solver:latest
          commonUpdateSettings:
            pullSecret: pullsecret:argocd/ghcr-pullsecret
