apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: guava
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: newest-build
    allowTags: "regexp:^.*$"
    pullSecret: pullsecret:argocd/ghcr-pullsecret
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: "guava"
      images:
        - alias: server
          imageName: ghcr.io/mmeinzer/guava
        - alias: solver
          imageName: ghcr.io/mmeinzer/guava-solver
